language: ruby
rvm:
- 2.3.1
install:
- travis_retry bundle install
script: bundle exec rspec
notifications:
  slack: "$SLACK_TOKEN"
  email: false
deploy:
  skip_cleanup: true
  provider: rubygems
  api_key:
    secure: MzTs9T5E7b6GoB6YP5/lzbNZm2EVGrjqM1QCqAAEDRnbUBLZhmuUI2ibcQeaL2QfzAHnbRKywt0UT8LWKqJ6uIS1XVGkWa9mPd2SoT1V3B8yGPqIp7xPCX9T6NeVDL7F5fAZB9k9uN8SbAY8CVN4gseLdYZuwtsTUpAyg87S2EkZvIHIfHeUQz87aDnCR7haN1d0CgcUuJLYDDGknYfkK7sHjJTehTMYEH2tByNhOVzmbmgO2uxUICUxrXpLVf2rXbWvuGqLtz5gf6GcQBIthOAKBGT3pYyHEQoSmu4FJro6lUpoOVEqdGRt2/LghUktuJzIdcfjAKn3YqVO+oFtXj9Kw+ON0H25pqhaEIhct9k9OjQRYHuDFAIHHAzG4+hz0rOvBlpGjiFkbZU4hkUJxnW/ATVNaghMzIjCkueKUplg1bkfpXeLMrb7IeULqOLfwmJirUaxcnVpf0hhVgDbtnaWwotxs9D4UWMZMSPmy2eumxu/NjfgFu5L8fYzm8z6/rbNcKTqQcSthIGCp+e/Sy6dtfd8SdZbtDJoSeA5FCWa6nQcN0lYO0evcAZ3+b6QfY17BEY15X4WHxt7fd6vnm0RjEZbftNFNfzZe08q5DdeRr8Y3DVNDWpqm1i5J3hobQ0lR3RkpLs4qinycaD6fRDBU/ZcvWUZtA+OdCT/YL8=
  gem: cirneco
  on:
    tags: true
    repo: datacite/cirneco
